spring.application.name=skill-9


server.port=8783

# Show detailed error messages (useful during development)
server.error.include-message=always

# Disable default whitelabel error page
server.error.whitelabel.enabled=false